# Sets up the deployment on CircleCI

version: 2.1

workflows:
  version: 2
  iris-dataset-classifier:
    jobs:
      - build


jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install python3 and pip3
          command:
            sudo apt-get install python3 python3-pip

      - run:
          name: Install requirements
          command:
            sudo python3 -m pip install -r requirements.txt
          when: always

      - run:
          name: Run pip3 freeze
          command: python3 -m pip freeze
          when: always

      - run:
          name: Run flake8
          command: python3 -m flake8
          when: always

      - run:
          name: Run the test suite
          command: python3 -m pytest
          when: always
