# Sets up the deployment on CircleCI

version: 2.1

executors:
  ubuntu_bionic:
    docker:
      - image: circleci/buildpack-deps:bionic


workflows:
  version: 2
  iris-dataset-classifier:
    jobs:
      - run_checks_and_test
      - build_and_push_docker

jobs:
  build_and_push_docker:
    executor: ubuntu_bionic
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Log in to DockerHub
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run:
          name: Build Dockerfile
          command: docker build -t justinchanjinle/iris-dataset-classifier:$CIRCLE_BRANCH --rm .

      - run:
          name: Push Dockerfile
          command: docker push justinchanjinle/iris-dataset-classifier:$CIRCLE_BRANCH

  run_checks_and_test:
    executor: ubuntu_bionic
    steps:
      - checkout
      - run:
          name: Install python3 and pip3
          command:
            sudo apt-get install python3 python3-pip

      - run:
          name: Install requirements
          command:
            sudo python3 -m pip install -r requirements.txt
          when: always

      - run:
          name: Run pip3 freeze
          command: python3 -m pip freeze
          when: always

      - run:
          name: Run flake8
          command: python3 -m flake8
          when: always

      - run:
          name: Run the test suite
          command: python3 -m pytest
          when: always
